### ISSUE TITLE
complaint about turning on hacks while chatting or on menu

### ISSUE THREAD

**Issue by booshican** [Flare-Client/Flare-Client#100]
for some reason things like FOV and jetpack will turn on while im using chat and if gets really annoying if there are things like lava in front of you

**Comment by EchoHackCmd** [comment]
The problem is getting a pointer which tells us when the chat is open or closed and using that to resolve this exact problem, However I will look into this further as it does get me too and I completely understand how aggravating it can be when all you're currently trying to do is chat and your player goes 200 miles per hour and throws them self of a cliff...

**Comment by Daxanius** [comment]
> The problem is getting a pointer which tells us when the chat is open or closed and using that to resolve this exact problem, However I will look into this further as it does get me too and I completely understand how aggravating it can be when all you're currently trying to do is chat and your player goes 200 miles per hour and throws them self of a cliff...

Since it is actually a program in and of itself and not an edited version of the game this is indeed a bit of a hassle to implement.

**Comment by DisabledMallis** [comment]
This will likely never be fixed due to the inactivity of development, closing
