### ISSUE TITLE
Click Targeting

### ISSUE THREAD

**Issue by Vbrawl** [Flare-Client/Flare-Client#104]
Recently I downloaded flare and looked all the modules and then i looked on the "target" menu and i think it would be better if you could use a button to add a target.

**Comment by EchoHackCmd** [comment]
There is a + button, maybe next time you should open your eyes instead of wasting other people's time having to look at your issue.

also this was removed in v0.0.7.1 due to the new entity list (Which only includes players and not other types of entities - also NPC's but the entity type for NPC's is a 'player')

**Comment by Vbrawl** [comment]
> There is a + button, maybe next time you should open your eyes instead of wasting other people's time having to look at your issue.
> 
> also this was removed in v0.0.7.1 due to the new entity list (Which only includes players and not other types of entities - also NPC's but the entity type for NPC's is a 'player')

I know there is a + button I just thought it would be better if you could press a button (ex. "V") while looking at a player to add him to the target list.

**Comment by 28xKwjIw** [comment]
Shh Case closed

**Comment by RoseIsSuicidal** [comment]
L
