### ISSUE TITLE
Gamemode not working?

### ISSUE THREAD

**Issue by ShadowPlay1392** [Flare-Client/Flare-Client#84]
so I turn on game mode and its set to 1 but I can't pull things out of the creative inventory on survival no cheats world I'm not sure if this is a bug or if this is how this works and It doesn't work the way I'm thinking it does

**Comment by EchoHackCmd** [comment]
The Gamemode module is a client sided module so you can't simply drag items from the Creative Inventory to the Survival inventory, However you can use the no Packet method in order to keep the items from disappearing but it only works for items that can only be crafted. Using the NoPacket method will not work on most Servers, in fact it only seems to work on single Player worlds, Xbox worlds, Realms and some Servers that use the vanilla inventory transactions such as Servers that run on the Bedrock dedicated Server Software.
